import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useSWR, { useSWRConfig } from "swr";

export default function Home() {
  /////for get req
  const fetcher = (...arg) => fetch(...arg).then((res) => res.json());

  /////for post req
  const { mutate } = useSWRConfig();
  let postObject = {
    headers: {
      Accept: "application/json;charset=UTF-8",
      "Content-Type": "application/json;charset=UTF-8",
    },
    method: "POST",
    body: JSON.stringify({
      channelId: 49326900,
      currency: "EUR",
      market: "SE",
      programId: [42014357, 1035156879],
      minAmount: 5000,
      maxAmount: 100000,
      acceptsRemarks: true,
    }),
  };
  let Url = "https://api.adtraction.com/v2/public/compare/loans/";

  
  const { data, error } = useSWR(
    "https://jsonplaceholder.typicode.com/todos/",
    fetcher
  );
  console.log(data, error);
  if (error) return "An error has occurred.";
  if (!data) return "Loading...";
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Post request with swr</h1>
        <button
          onClick={() => {
            fetcher(Url, postObject);
            console.log("mutating");
            mutate("https://jsonplaceholder.typicode.com/todos/");
          }}
        >
          post data
        </button>
      </main>
    </div>
  );
}